version: '3.10'

services:
  long_llm:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: long_llm
    volumes:
      - ./hf_cache:/root/.cache/huggingface/
      - ./data:/app/data
      - ./output:/app/output
    environment:
      - CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
    ports:
      - "7860:7860"
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: "all"
            capabilities: [gpu]
    restart: unless-stopped
